# cloudbuild yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  env:
    - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
    - CLOUDSDK_CONTAINER_CLUSTER=test-cluster-1
    - CLOUDSDK_CORE_PROJECT=windy-raceway-283505
  args: [ 'build', '-t', 'gcr.io/PROJECT_ID/IMAGE_NAME', '.' ]
